ALTER TABLE issue
ADD COLUMN IF NOT EXISTS selector TEXT[] NOT NULL,
ADD COLUMN IF NOT EXISTS relative_x NUMERIC NOT NULL,
ADD COLUMN IF NOT EXISTS relative_y NUMERIC NOT NULL,
ADD COLUMN IF NOT EXISTS element_height NUMERIC NOT NULL,
ADD COLUMN IF NOT EXISTS element_width NUMERIC NOT NULL,
ADD COLUMN IF NOT EXISTS viewport_height INTEGER NOT NULL,
ADD COLUMN IF NOT EXISTS viewport_width INTEGER NOT NULL;
